### ISSUE TITLE
Fault in to_numpy.py

### ISSUE THREAD

**Issue by bsteenwi** [dhruvramani/Multilabel-Classification-Datasets#1]
Hi,

When running your to_numpy.py code, I could not find the import related to Parser().get_parser().

https://github.com/dhruvramani/Multilabel-Classification-Datasets/blob/4d996973c40d5bf47d131ae698084539af2cbf7e/to_numpy.py#L25

I've locally changed this code to the parser defined on line 23, and this works....

**Comment by dhruvramani** [comment]
Thanks for pointing out, it was a typo.
